import { writeFile, chmod } from 'node:fs/promises';
import { join } from 'node:path';
import type { EnvPaths } from '../paths.js';

/**
 * Write a PowerShell script (and a .cmd wrapper) into <env>/database/ that:
 *   1. imports the .bacpac into LocalDB under a temporary database name
 *   2. detaches it
 *   3. moves + renames the resulting .mdf/.ldf into <env>/repo/umbraco/Data/
 *      as Umbraco.mdf / Umbraco_log.ldf
 *
 * The script self-locates relative to its own path so the user doesn't have
 * to fiddle with arguments.
 */
export async function writeLocalDbRestoreScript(
  paths: EnvPaths,
  databaseName: string,
): Promise<void> {
  const ps1 = buildPs1(databaseName);
  const cmd = buildCmd();

  const ps1Path = join(paths.database, 'restore-to-localdb.ps1');
  const cmdPath = join(paths.database, 'restore-to-localdb.cmd');

  await writeFile(ps1Path, ps1, 'utf8');
  await writeFile(cmdPath, cmd, 'utf8');

  if (process.platform !== 'win32') {
    // Just for completeness; LocalDB is Windows-only but the .ps1 might still
    // be inspected on other platforms.
    await chmod(ps1Path, 0o644).catch(() => undefined);
    await chmod(cmdPath, 0o644).catch(() => undefined);
  }
}

function buildPs1(databaseName: string): string {
  return `<#
.SYNOPSIS
  Restore the archived Umbraco Cloud database to LocalDB and place the data
  files inside the repo working copy as umbraco\\Data\\Umbraco.mdf /
  umbraco\\Data\\Umbraco_log.ldf so Umbraco Deploy's
  PreferLocalDbConnectionString = true picks it up.

.NOTES
  Generated by umbraco-cloud-archiver. Run from this folder:
      powershell -ExecutionPolicy Bypass -File .\\restore-to-localdb.ps1
  or just double-click restore-to-localdb.cmd.
#>

[CmdletBinding()]
param(
  [string]$BacpacFile = "${databaseName}.bacpac",
  [string]$TempDbName = "UmbracoRestore_\$([Guid]::NewGuid().ToString('N').Substring(0,8))",
  [string]$LocalDbInstance = "MSSQLLocalDB"
)

\$ErrorActionPreference = 'Stop'

function Resolve-Sqlpackage {
  \$inPath = Get-Command sqlpackage -ErrorAction SilentlyContinue
  if (\$inPath) { return \$inPath.Path }

  # Fall back to umbraco-cloud-archiver's cache.
  \$cache = Join-Path \$env:USERPROFILE '.umbraco-cloud-archiver\\bin\\sqlpackage'
  if (Test-Path \$cache) {
    \$candidate = Get-ChildItem -Path \$cache -Recurse -Filter 'sqlpackage.exe' -ErrorAction SilentlyContinue |
                  Select-Object -First 1
    if (\$candidate) { return \$candidate.FullName }
  }
  throw "sqlpackage was not found in PATH or in ~\\.umbraco-cloud-archiver\\bin\\sqlpackage. Install it and try again."
}

function Resolve-Sqlcmd {
  \$inPath = Get-Command sqlcmd -ErrorAction SilentlyContinue
  if (\$inPath) { return \$inPath.Path }
  throw "sqlcmd was not found in PATH. Install SQL Server command-line tools (sqlcmd) and try again."
}

\$here = Split-Path -Parent \$MyInvocation.MyCommand.Path
\$bacpac = Join-Path \$here \$BacpacFile
if (-not (Test-Path \$bacpac)) {
  throw "Bacpac not found: \$bacpac"
}

# Working copy: <env>/database/.. = <env>; then /repo/umbraco/Data
\$envRoot   = Split-Path -Parent \$here
\$repoRoot  = Join-Path \$envRoot 'repo'
if (-not (Test-Path \$repoRoot)) {
  throw "Repo working copy not found at \$repoRoot - cannot deploy LocalDB files."
}
\$umbDataDir = Join-Path \$repoRoot 'umbraco\\Data'
if (-not (Test-Path \$umbDataDir)) {
  Write-Host "Creating \$umbDataDir"
  New-Item -ItemType Directory -Path \$umbDataDir | Out-Null
}

\$mdfTarget = Join-Path \$umbDataDir 'Umbraco.mdf'
\$ldfTarget = Join-Path \$umbDataDir 'Umbraco_log.ldf'
if ((Test-Path \$mdfTarget) -or (Test-Path \$ldfTarget)) {
  throw "Existing Umbraco.mdf or Umbraco_log.ldf already in \$umbDataDir. Remove them first to avoid overwriting your data."
}

\$sqlpackage = Resolve-Sqlpackage
\$sqlcmd     = Resolve-Sqlcmd
Write-Host "Using sqlpackage: \$sqlpackage"
Write-Host "Using sqlcmd:     \$sqlcmd"

# 1. Make sure LocalDB is running.
& sqllocaldb start \$LocalDbInstance | Out-Null

\$serverConn = "(LocalDb)\\\$LocalDbInstance"
\$cs = "Server=\$serverConn;Database=\$TempDbName;Integrated Security=true;TrustServerCertificate=true;"

Write-Host "Importing \$BacpacFile into LocalDB as \$TempDbName ..."
& \$sqlpackage /Action:Import /SourceFile:\$bacpac /TargetConnectionString:"\$cs"
if (\$LASTEXITCODE -ne 0) { throw "sqlpackage import failed (\$LASTEXITCODE)." }

# 2. Read physical file paths before detaching.
\$queryPaths = "SET NOCOUNT ON; SELECT physical_name FROM sys.master_files WHERE database_id = DB_ID('\$TempDbName') ORDER BY type;"
\$physical = & \$sqlcmd -S \$serverConn -d master -E -h -1 -W -Q \$queryPaths
if (\$LASTEXITCODE -ne 0) { throw "sqlcmd failed reading file paths." }

\$paths = \$physical | Where-Object { \$_ -and \$_.Trim() -ne '' -and -not \$_.StartsWith('-') }
if (\$paths.Count -lt 2) {
  throw "Could not determine .mdf / .ldf paths. sqlcmd output: \$physical"
}
\$mdfSource = \$paths[0].Trim()
\$ldfSource = \$paths[1].Trim()
Write-Host "Database files:"
Write-Host "  data: \$mdfSource"
Write-Host "  log : \$ldfSource"

# 3. Detach.
Write-Host "Detaching \$TempDbName ..."
\$detach = "ALTER DATABASE [\$TempDbName] SET SINGLE_USER WITH ROLLBACK IMMEDIATE; EXEC sp_detach_db '\$TempDbName';"
& \$sqlcmd -S \$serverConn -d master -E -Q \$detach
if (\$LASTEXITCODE -ne 0) { throw "Detach failed." }

# 4. Move + rename into repo's umbraco\\Data.
Write-Host "Moving files into \$umbDataDir ..."
Move-Item -Path \$mdfSource -Destination \$mdfTarget
Move-Item -Path \$ldfSource -Destination \$ldfTarget

Write-Host ""
Write-Host "Done."
Write-Host "  - \$mdfTarget"
Write-Host "  - \$ldfTarget"
Write-Host ""
Write-Host "Next: ensure your appsettings has Umbraco:Deploy:Settings:PreferLocalDbConnectionString = true,"
Write-Host "then 'dotnet run' from \$repoRoot."
`;
}

function buildCmd(): string {
  // Simple wrapper that lets the user double-click. Uses -NoProfile and bypasses
  // execution policy for this one invocation.
  return `@echo off
powershell.exe -NoProfile -ExecutionPolicy Bypass -File "%~dp0restore-to-localdb.ps1" %*
pause
`;
}
